import Product1 from "./Category/img/cat27.jpg";
import Product2 from "../components/Category/img/p1.png";
import Product3 from "../components/Category/img/p2.png";
import Product4 from "../components/Category/img/p12.png";
import Product5 from "../components/Category/img/p4.png";
import Product6 from "../components/Category/img/p13.png";
import Product7 from "../components/Category/img/p6.png";
import Product8 from "../components/Category/img/p7.png";
import Product9 from "../components/Category/img/p8.png";
import Product10 from "../components/Category/img/p9.png";
import Product11 from "../components/Category/img/p10.png";
import Product12 from "../components/Category/img/p11.png";
export const Items = [
  {
    id: 1,
    productName: "Dino Whole Foods Non Veg Plan",
    price: 300,
    description:'Pedigree Adult Dry Dog Food ',
    category:"Dog",
    productImage: Product1,
  },
  {
    id: 2,
    productName: "DINO WHOLE FOODS",
    price: 850,
    description:'Pedigree Adult Dry Dog Food',
    category:"Dog",
    productImage: Product2,
  },
  {
    id: 3,
    productName: "DINO WHOLE FOODS",
    price: 1250,
    description:'Pedigree Adult Dry Dog ',
    category:"Dog",
    productImage: Product3,
  },
  {
    id: 4,
    productName: "DINO WHOLE FOODS ",
    price: 500,
    description:'Pedigree Adult Dry Dog ',
    category:"Dog",
    productImage: Product4,
  },
  {
    id: 5,
    productName: "DINO WHOLE FOODS",
    price: 600,
    description:'Pedigree Adult Dry Dog ',
    category:"Dog",
    productImage: Product5,
  },
  {
    id: 6,
    productName: "DINO WHOLE FOODS NON VEG PLAN",
    price: 450,
    description:'Pedigree Adult Dry Dog ',
    category:"Dog",
    productImage: Product6,
  },
  {
    id: 7,
    productName: "DINO WHOLE FOODS NON VEG PLAN",
    price: 1100,
    description:'Pedigree Adult Dry Dog ',
    category:"Dog",
    productImage: Product7,
  },
  {
    id: 8,
    productName: "DINO WHOLE FOODS NON VEG PLAN",
    price: 800,
    description:'Pedigree Adult Dry Dog k',
    category:"Cat",
    productImage: Product8,
  },
  {
    id: 9,
    productName: "DINO WHOLE FOODS NON VEG PLAN",
    price: 850,
    description:'Pedigree Adult Dry Dog ',
    category:"Cat",
    productImage: Product9,
  },
  {
    id: 10,
    productName: "DINO WHOLE FOODS NON VEG PLAN",
    price: 625,
    description:'Pedigree Adult Dry Dog ',
    category:"Cat",
    productImage: Product10,
  },
  {
    id: 11,
    productName: "DINO WHOLE FOODS NON VEG PLAN",
    price: 900,
    description:'Pedigree Adult Dry Dog ',
    category:"Dog",
    productImage: Product11,
  },
  {
    id: 12,
    productName: "DINO WHOLE FOODS NON VEG PLAN",
    price: 750,
    description:'Pedigree Adult Dry Dog ',
    category:"Cat",
    productImage: Product12,
  },
  // {
  //   id: 13,
  //   productName: "DINO WHOLE FOODS NON VEG PLAN",
  //   price: 425,
  //   description:'Pedigree Adult Dry Dog',
  //   category:"Cat",
  //   productImage: Product13,
  // },
  // {
  //   id: 14,
  //   productName: "DINO WHOLE FOODS NON VEG PLAN",
  //   price: 425,
  //   description:'Pedigree Adult Dry Dog ',
  //   category:"Cat",
  //   productImage: Product14,
  // },
  // {
  //   id: 15,
  //   productName: "DINO WHOLE FOODS NON VEG PLAN",
  //   price: 425,
  //   description:'Pedigree Adult Dry Dog ',
  //   category:"Cat",
  //   productImage: Product15,
  // },
  // {
  //   id: 16,
  //   productName: "DINO WHOLE FOODS NON VEG PLAN",
  //   price: 425,
  //   description:'Pedigree Adult Dry Dog ',
  //   category:"Cat",
  //   productImage: Product16,
  // },
  // {
  //   id: 17,
  //   productName: "DINO WHOLE FOODS NON VEG PLAN",
  //   price: 425,
  //   description:'Pedigree Adult Dry Dog ',
  //   category:"Cat",
  //   productImage: Product17,
  // },
  // {
  //   id: 18,
  //   productName: "DINO WHOLE FOODS NON VEG PLAN",
  //   price: 425,
  //   description:'Pedigree Adult Dry Dog ',
  //   category:"Cat",
  //   productImage: Product18,
  // },
  // {
  //   id: 19,
  //   productName: "DINO WHOLE FOODS NON VEG PLAN",
  //   price: 425,
  //   description:'Pedigree Adult Dry Dog ',
  //   category:"Cat",
  //   productImage: Product19,
  // },
  // {
  //   id: 20,
  //   productName: "DINO WHOLE FOODS NON VEG PLAN",
  //   price: 425,
  //   description:'Pedigree Adult Dry Dog ',
  //   category:"Cat",
  //   productImage: Product20,
  // },
  // {
  //   id: 21,
  //   productName: "DINO WHOLE FOODS NON VEG PLAN",
  //   price: 425,
  //   description:'Pedigree Adult Dry Dog ',
  //   category:"Cat",
  //   productImage: Product21,
  // },
  // {
  //   id: 22,
  //   productName: "DINO WHOLE FOODS NON VEG PLAN",
  //   price: 425,
  //   description:'Pedigree Adult Dry Dog ',
  //   category:"Cat",
  //   productImage: Product22,
  // },
  // {
  //   id: 23,
  //   productName: "DINO WHOLE FOODS NON VEG PLAN",
  //   price: 425,
  //   description:'Pedigree Adult Dry Dog ',
  //   category:"Cat",
  //   productImage: Product23,
  // },
  
];
